baseURL = 'https://crmejia.github.io'
languageCode = 'en-us'
title = 'Crismar.Me'

theme = "ananke"

[[params.topmenu]]
name = "about"
url = "about/"

[[params.topmenu]]
name = "blog"
url = "posts/"

[[params.topmenu]]
name = "consulting"
url = "consulting/"

[services]
[services.googleAnalytics]
ID = 'G-CDK4087KM8'
